### ISSUE TITLE
Support for Go?

### ISSUE THREAD

**Issue by HexHash64** [RRUZ/wmi-delphi-code-creator#13]
Have you ever considered adding Go as a supported language to WMI Delphi Code Creator? The 'StackExchange' account has a great example of querying WMI with Go:
https://github.com/StackExchange/wmi

Or another approach here: https://libraries.io/github/a-palchikov/wmi

**Comment by RRUZ** [comment]
Hi, there are no plans for now to add new languages to the project. But any contributions are very welcome ;)
