### ISSUE TITLE
Dose not compile under XE

### ISSUE THREAD

**Issue by limelect** [RRUZ/wmi-delphi-code-creator#14]
Dose not compile under XE.
Took the demo and tried to compile with xe
I started fixing but to many errors.
Specially style.
Gave up.
Plz make an XE version

**Comment by RRUZ** [comment]
Can you please attach a  code generated which not compile under XE.

**Comment by limelect** [comment]
1. No style on xe. Any thing with the word STYLE dose not compile.
2. All uses have to change from ,for example , Winapi.Windows > Windows
 
I used WDCC.dpr to compile as a demo

**Comment by RRUZ** [comment]
The WDCC was compiled using XE4, So in order to compile you need that version at least. Anyway you don't need compile your self the WDCC application to generate WMI Code, only you need install the binaries directly using the installer,
