### ISSUE TITLE
Win32_networkadapterconfiguration in delphi

### ISSUE THREAD

**Issue by cbartholo** [RRUZ/wmi-delphi-code-creator#15]
Hi,
i choose win32_networkadapetrconfiguration with the properties, ipaddress and mac.
when i save the file and run it with Delphi XE8, i always get:
EVariantTypeCastError:  could not convert variant of type (Null) into type (Olestr).
Whats wrong here ?
I am using version 1.9.5.0

**Comment by RRUZ** [comment]
This kind of error appears when the value returned by a property is null , You can use the VarIsNull function to check and the VarToStr methods to handle this situation.
