### ISSUE TITLE
C++ returns wrong UINT64 values

### ISSUE THREAD

**Issue by fox1406** [RRUZ/wmi-delphi-code-creator#23]
In C++ when reading UINT64 values from VARIANT structure, you should use bstrVal instead of uintVal. You can see more about the issue here: http://www.codeproject.com/Questions/384313/Cplusplus-WMI-UINT-question

Hope you fix this in next update,
Thanks!

**Comment by RRUZ** [comment]
Thanks for the report, I just fixed the issue. Please try the new version.
