### ISSUE TITLE
Invalid URL in README.md

### ISSUE THREAD

**Issue by Crayon2000** [RRUZ/wmi-delphi-code-creator#25]
The link to [Binaries (Portable edition)](http://goo.gl/800XwT) is broken in the [README.md](https://raw.githubusercontent.com/RRUZ/wmi-delphi-code-creator/master/README.md) file.

The same link is also used on your [web site](https://theroadtodelphi.com/wmi-delphi-code-creator/). Also resulting in a Error 404 page.

**Comment by RRUZ** [comment]
Thanks, for the report,  Unfortunately the portable edition is not longer supported.
